import:
 - ~/.alacritty-nord.yml

env:
  TERM: alacritty

window:
  padding:
   x: 5
   y: 5
  dynamic_padding: true
  decorations: buttonless
  opacity: 0.9

font:
  normal:
    family: FiraCode Nerd Font Mono
  size: 14.0
  draw_bold_text_with_bright_colors: true
